---
- name: Register k8s master
  hosts: localhost
  gather_facts: true
  roles:
    - register-master

- name: Register k8s nodes
  hosts: localhost
  gather_facts: true
  roles:
    - register-nodes

- name: Reregister k8s nodes
  hosts: nodes
  gather_facts: true
  roles:
    - register-nodes-hostname

- name: Drain node
  hosts: master
  tags:
    - bootstrap
  roles:
    - remove-node