---
- name: copy manifests
  copy:
    src: "{{ role_path }}/files/"
    dest: "/home/ubuntu/manifests/"

- name: apply k8s-auth-policy.yaml
  command: kubectl apply -f /home/ubuntu/manifests/k8s-auth-policy.yaml

