- name: launch
  hosts: localhost
  tasks:
    - name: launch an instance
      os_server:
        state: present
        name: vm1
        image: ubuntu-14.04-server-cloudimg-amd64-disk1
        key_name: rvl
        timeout: 200
        flavor: m1.small
        security_groups: default
        auto_ip: yes
        network: mgmt
